INSERT INTO team_names(label)
VALUES
    ('Galactic Warriors'),
    ('The Alderaanian Resistance'),
    ('The Battle of Crait'),
    ('The Battle of Endor'),
    ('The Battle of Exegol'),
    ('The Battle of Hoth'),
    ('The Battle of Jakku'),
    ('The Battle of Scarif'),
    ('The Battle of Starkiller Base'),
    ('The Battle of Yavin'),
    ('The Black Squadron'),
    ('The Black Sun Syndicate'),
    ('The Blue Squadron'),
    ('The Bronze Squadron'),
    ('The Clone Troopers'),
    ('The Clone Wars'),
    ('The Cloud City'),
    ('The Dagobah Swamp'),
    ('The Dark Jedi'),
    ('The Dark Side'),
    ('The Death Star'),
    ('The Diamond Squadron'),
    ('The Empire Strikes Back'),
    ('The Endor Forest'),
    ('The First Order'),
    ('The First Order Stormtroopers'),
    ('The Force is Strong'),
    ('The Galactic Adventurers'),
    ('The Galactic Knights'),
    ('The Galactic Legion'),
    ('The Galactic Outlaws'),
    ('The Galactic Patriots'),
    ('The Galactic Protectors'),
    ('The Galactic Warriors'),
    ('The Gold Squadron'),
    ('The Gray Squadron'),
    ('The Green Squadron'),
    ('The Hoth Squad'),
    ('The Imperial Commandos,'),
    ('The Imperial Fleets'),
    ('The Imperial Walkers'),
    ('The Imperials'),
    ('The Jabba Palace'),
    ('The Jedi Archers'),
    ('The Jedi Blademasters'),
    ('The Jedi Council'),
    ('The Jedi Exile'),
    ('The Jedi Knights'),
    ('The Jedi Masters'),
    ('The Jedi Navigators'),
    ('The Jedi Revenants'),
    ('The Jedi Ronin'),
    ('The Jedi Sentinels'),
    ('The Jedi Shadows'),
    ('The Jedi Wardens'),
    ('The Knights of Ren'),
    ('The Kyber Crystal Commandos'),
    ('The Light Side'),
    ('The Mandalorian Mercenaries'),
    ('The Millennium Falcon'),
    ('The Mos Eisley Cantina'),
    ('The Orange Squadron'),
    ('The Pearl Squadron'),
    ('The Pink Squadron'),
    ('The Purple Squadron'),
    ('The Rebel Alliance'),
    ('The Rebel Guerillas'),
    ('The Rebel Scum'),
    ('The Rebel Squadrons'),
    ('The Red Squadron'),
    ('The Republic Cruisers'),
    ('The Republic Defenders'),
    ('The Resistance'),
    ('The Resistance Pilots'),
    ('The Rogue Squadron'),
    ('The Ruby Squadron'),
    ('The Sapphire Squadron'),
    ('The Silver Squadron'),
    ('The Sith Apprentices'),
    ('The Sith Assassins'),
    ('The Sith Cartographers'),
    ('The Sith Enforcers'),
    ('The Sith Lords'),
    ('The Sith Lords of the Night'),
    ('The Sith Marauders'),
    ('The Sith Order'),
    ('The Sith Shadows'),
    ('The Sith Warriors'),
    ('The Sith Wizards'),
    ('The Starkiller Base'),
    ('The Wookie Warriors'),
    ('The Yellow Squadron'),
    ('TIE Fighters'),
    ('X-Wing Fighters');